server.port: 8086

solon.app:
  name: 'demo-app'
  group: 'demo'


#liteflow配置
liteflow:
  rule-source: "config/flow.el.xml"

# 数据库配置
db:
  url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456

# Redis配置
redis:
  host: localhost
  port: 6379
  password:  # 如果没有密码可以留空
  database: 0
  timeout: 10000
  lettuce:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0



